### ISSUE TITLE
TypeError: getaddrinfo() argument 1 must be string or None

### ISSUE THREAD

**Issue by kamikaze** [nateshmbhat/webbot#29]
after replacing chrome_driver with arm64 version I'm getting next issue:

```
Python 3.8.0 (default, Nov 19 2019, 12:46:48)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from webbot import Browser
>>> web = Browser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.venv38/lib/python3.8/site-packages/webbot/webbot.py", line 52, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath , chrome_options=options)
  File "/.venv38/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 78, in __init__
    command_executor=ChromeRemoteConnection(
  File "/.venv38/lib/python3.8/site-packages/selenium/webdriver/chrome/remote_connection.py", line 24, in __init__
    RemoteConnection.__init__(self, remote_server_addr, keep_alive)
  File "/.venv38/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 119, in __init__
    ip = common_utils.find_connectable_ip(parsed_url.hostname,
  File "/.venv38/lib/python3.8/site-packages/selenium/webdriver/common/utils.py", line 72, in find_connectable_ip
    connectable = is_connectable(port, sockaddr[0])
  File "/.venv38/lib/python3.8/site-packages/selenium/webdriver/common/utils.py", line 106, in is_connectable
    socket_ = socket.create_connection((host, port), 1)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
TypeError: getaddrinfo() argument 1 must be string or None
```

**Comment by kamikaze** [comment]
FYI: https://github.com/SeleniumHQ/selenium/issues/7848
