### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lobatim** [nateshmbhat/webbot#49]
I get this error when I whrite: from webbot import Browser

from webbot import browser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\paulo\Desktop\webbot-master\webbot-master\webbot\__init__.py", line 1, in <module>
    from .webbot import Browser
  File "C:\Users\paulo\Desktop\webbot-master\webbot-master\webbot\webbot.py", line 42
    def __init__(self , showWindow = True , proxy = None ):
    ^

**Comment by Paszymaja** [comment]
#50 Created pull request with fix
