### ISSUE TITLE
Cannot install with pip or git in command line

### ISSUE THREAD

**Issue by mstewart2150** [nateshmbhat/webbot#56]
Hello,

I am having issues trying to install the package to my RPi. I have tried both 'pip install webbot' and 'python -m pip install git+https://github.com/nateshmbhat/webbot.git'. I get similar messages which are listed below:

`pip install webbot`

`
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
`

`
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
`

`
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
`

`
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
`

`
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
`

`
Collecting webbot
  Using cached webbot-0.34.tar.gz (12.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-KP_5mI/webbot/setup.py'"'"'; __file__='"'"'/tmp/pip-install-KP_5mI/webbot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-UKP1LA
         cwd: /tmp/pip-install-KP_5mI/webbot/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-KP_5mI/webbot/setup.py", line 8, in <module>
        with open('README.rst', 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Can anyone assist with this issue? It looks like the computer is hung up on the encoding argument when trying to set up the package. I am excited to try this package out, so any assistance would be great. Thanks!

**Comment by soarn** [comment]
bump.

**Comment by soarn** [comment]
@mstewart2150 Try: `py -m pip install webbot`
