### ISSUE TITLE
Code 127 on fresh Ubuntu LTS Server

### ISSUE THREAD

**Issue by Davewesh** [nateshmbhat/webbot#61]
Running any of the sample code or the code from my project yields the same result regardless if invoked through sudo or otherwise. 

```
from webbot import Browser
driver = Browser(showWindow=False) 
#This has already been tested with the default __init__ "showWindow=True" and yeilds the same result.
```
Returns the following: 
```
daweshen@discordbot:~/DiscordBot$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    driver = Browser(showWindow=False)
  File "/home/daweshen/.local/lib/python3.8/site-packages/webbot/webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "/home/daweshen/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/daweshen/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/daweshen/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/daweshen/.local/lib/python3.8/site-packages/webbot/drivers/chrome_linux unexpectedly exited. Status code was: 127
```

Checking for Chromium Driver installation: 
```
daweshen@discordbot:~/DiscordBot$ sudo snap install chromium
snap "chromium" is already installed, see 'snap help refresh'
daweshen@discordbot:~/DiscordBot$ sudo apt-get install -y chromium-browser
Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-browser is already the newest version (1:85.0.4183.83-0ubuntu0.20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 78 not upgraded.
```

Not sure what other information would be needed to assist with this. I could probably pull down 18.04 LTS and give that a whirl if its a versioning issue between Ubuntu 20 and 18. I know that this had no issues on my Win10 Desktop, so not 100% sure where to look here or if this is an inherent problem with my Ubuntu deployment being headless. Any guidance would be appreciated!

**Comment by WaterZ-dev** [comment]
i have the same exact error :(

**Comment by AzlanCoding** [comment]
Me too 😭
