### ISSUE TITLE
Webbot is not working on linux(parrot)

### ISSUE THREAD

**Issue by Slakesslumban** [nateshmbhat/webbot#74]
┌─[✗]─[nawnit@asus]─[~]
└──╼ $python /home/nawnit/Desktop/python3.py
Traceback (most recent call last):
  File "/home/nawnit/Desktop/python3.py", line 4, in <module>
    driver = Browser()
  File "/home/nawnit/.local/lib/python3.9/site-packages/webbot/webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 5.10.0-6parrot1-amd64 x86_64)

**Comment by manwapri** [comment]
Perform step no 3 to 6,
You need to find the installation location of webbot.


Step 1: Open cmd and fire pip command
pip install webbot

Step 2: check your chrome version
go to Menu -> Help -> About Google Chrome

Step 3: Download chrome driver as per the chrome version from below link
https://sites.google.com/a/chromium.org/chromedriver/downloads

Step 4: extract the driver file and save it to,
C:\Users%USERNAME%\AppData\Local\Programs\Python\Python39\lib\site-packages\webbot\drivers\

Step 5: In drivers forlder, make copy of chrome_windows (Simply copy the file & paste it in same folder)
new file will be like "chrome_windows - Copy.exe"
and delete the original "chrome_windows.exe"

Step 6: Rename the extracted file "chromedriver.exe" to "chrome_windows.exe"

**Comment by carloalbertogiordano** [comment]
If you are working under linux you actually need to rename the chrome driver to chrome_linux, not chrome_windows.exe
Also from what I understand you can keep it in your project folder. Hope it helps

**Comment by nrnw** [comment]
> Perform step no 3 to 6, You need to find the installation location of webbot.
> 
> Step 1: Open cmd and fire pip command pip install webbot
> 
> Step 2: check your chrome version go to Menu -> Help -> About Google Chrome
> 
> Step 3: Download chrome driver as per the chrome version from below link https://sites.google.com/a/chromium.org/chromedriver/downloads
> 
> Step 4: extract the driver file and save it to, C:\Users%USERNAME%\AppData\Local\Programs\Python\Python39\lib\site-packages\webbot\drivers\
> 
> Step 5: In drivers forlder, make copy of chrome_windows (Simply copy the file & paste it in same folder) new file will be like "chrome_windows - Copy.exe" and delete the original "chrome_windows.exe"
> 
> Step 6: Rename the extracted file "chromedriver.exe" to "chrome_windows.exe"

New driver download page
https://sites.google.com/chromium.org/driver/?pli=1
