### ISSUE TITLE
session not created exception: Missing or invalid capabilities

### ISSUE THREAD

**Issue by evenmm** [nateshmbhat/webbot#85]
Running Ubuntu 20.04.4 LTS (Focal Fossa).

**Code:** 
from webbot import Browser
web = Browser()

**Error:** 
Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    web = Browser()
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/webbot/webbot.py", line 80, in __init__
    self.driver = webdriver.Chrome(executable_path=driverPath, options=options)
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/evenmm/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 5.16.19-76051619-generic x86_64)

**Comment by shasherazi** [comment]
same issue here

**Comment by codyandersan** [comment]
I am also having the same issue on Windows 10. Please tell how to fix it.
