### ISSUE TITLE
Web = Browser() , Error 

### ISSUE THREAD

**Issue by Tecspay** [nateshmbhat/webbot#93]
What do I do ?? It shows Web = Browser() , Error

**Comment by jayyoung12643** [comment]
I get the same issue - follow the documentation for installation, try the demo code and get an error on 2nd line of code..

"web = Browser()"

"
Traceback (most recent call last):
  File "C:\Users\jayyo\OneDrive\Documents\KCL\LSF webbot", line 10, in <module>
    web = Browser()
  File "C:\Users\jayyo\AppData\Local\Programs\Python\Python39\lib\site-packages\webbot\webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "C:\Users\jayyo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\jayyo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\jayyo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\jayyo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jayyo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.19045 x86_64)

[Finished in 7.7s]
"

**Comment by jemaleng** [comment]
See : https://stackoverflow.com/questions/76550506/typeerror-webdriver-init-got-an-unexpected-keyword-argument-executable-p

Looks like it relates to an update of selenium. I'm afraid that the library needs correction. I have the same issue.

**Comment by ercag** [comment]
any update about this problem?
looks like selenium changed the cunstructor and executable_path is not necessary any more...

**Comment by pidgeon777** [comment]
Yes, please an update?

**Comment by pidgeon777** [comment]
After a good amount of work I was able to fix it somehow, you can find a guide I just wrote here:

https://github.com/nateshmbhat/webbot/issues/95

Hopefully it will be useful to all of you.

**Comment by rayud** [comment]
Could anyone kindly explain what is the resolution for this??
