### ISSUE TITLE
When I try to do web = Browser() I get this error: ValueError: Timeout value connect was <object object at 0x00000277138947B0>, but it must be an int, float or None.

### ISSUE THREAD

**Issue by HerrKallupke** [nateshmbhat/webbot#94]
This is all my code:

from webbot import Browser

web = Browser()

and this is the error:

ValueError: Timeout value connect was <object object at 0x00000277138947B0>, but it must be an int, float or None.

**Comment by pidgeon777** [comment]
I also have this problem.

I solved it by doing:

```batch
pip3 uninstall selenium
pip3 install selenium==4.9.0
```

but now this error occurs:

```log
DevTools listening on ws://127.0.0.1:52778/devtools/browser/5d9c3a89-6891-4fef-a461-f0422ca64582
[0213/092047.845:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Traceback (most recent call last):
  File "C:\Work\Scripts\Python\leavetime.py", line 28, in <module>
    web = Browser(showWindow=False)
  File "C:\Users\<my_username>\scoop\apps\miniconda3\current\envs\webbot\lib\site-packages\webbot\webbot.py", line 72, in __init__
    [setattr(self, function, getattr(self.driver, function)) for function in
  File "C:\Users\<my_username>\scoop\apps\miniconda3\current\envs\webbot\lib\site-packages\webbot\webbot.py", line 72, in <listcomp>
    [setattr(self, function, getattr(self.driver, function)) for function in
AttributeError: 'WebDriver' object has no attribute 'switch_to_alert'
```

**Comment by HerrKallupke** [comment]
I really don't know what is going on I'd recommend to just use bs4 or something like that

**Comment by pidgeon777** [comment]
After a good amount of work I was able to fix it somehow, you can find a guide I just wrote here:

https://github.com/nateshmbhat/webbot/issues/95

Hopefully it will be useful to all of you.

**Comment by pidgeon777** [comment]
Also I converted my script to "pure" Selenium version, it seems to run faster/better now.
